apiVersion: v1
kind: Pod
metadata:
  name: dsnet
spec:
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
    - hostPath:
        path: /datashare
      name: datashare
    - hostPath:
        path: /users
      name: users
 
  securityContext:
    runAsUser: 119
    fsGroup: 119
 
  restartPolicy: Never
 
  imagePullSecrets:
  - name: regcred
 
  containers:
    - name: ocnet
      image: ascent-docker.zapto.org:443/ocnet
      command: ["/bin/bash"]
      args: ["-c", "cd /users/sang/works/drivablenet; make train"]
      extendedResourceRequests: ["nvidia-gpu"]
 
      resources:
        requests:
          cpu: "10"
          memory: "32Gi"
        limits:
          cpu: "12"
          memory: "64Gi"
 
      volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /datashare
        name: datashare
      - mountPath: /users
        name: users
         
  extendedResources:
    - name: "nvidia-gpu"
      resources:
        limits:
          nvidia.com/gpu: 2
      affinity:
        required:
          - key: "nvidia.com/gpu-memory"
            operator: "Gt"
            values: ["32000"]
